[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]
edition = "2018"

[dependencies]
lazy_static = "1"
regex = "1.0"
tera = "1"
image = { version = "0.23.13", features = ["avif"] }
rayon = "1"

errors = { path = "../errors" }
utils = { path = "../utils" }
